version: 11.5.{build}

image: Visual Studio 2013

shallow_clone: true

environment:
  matrix:
    - PLATFORM: x86
      VCVARSALL_PLATFORM: x86
      GENERATOR: "Visual Studio 12"
    - PLATFORM: x64
      VCVARSALL_PLATFORM: x86_amd64
      GENERATOR: "Visual Studio 12 Win64"

init:
# Make VS 2013 command line tools available
- call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %VCVARSALL_PLATFORM%

install:
# We need to install NSIS to create the packaged installer executable.
- choco install nsis-unicode -y

# Move all woking directory items except `appveyor.yml` to `love` subdirectory.
- md love
- for /D %%i in (*) do @if "%%i" NEQ "love" @move %%i love\%%i
- for %%i in (*) do @if "%%i" NEQ "appveyor.yml" @move %%i love\%%i
# clone megasource and move into top directory.
- git clone --depth 1 https://github.com/love2d/megasource.git megasource
- cd megasource
- for /D %%i in (*) do @move %%i ..\%%i
- for %%i in (*) do @move %%i ..\%%i
- cd ..
# move love source to megasource's libs\love.
- move love libs\love

before_build:
- cmake -G "%GENERATOR%" -H. -Bbuild

build_script:
- cmake --build build --target PACKAGE --config Release

after_build:

before_test:

test_script:

artifacts:
- path: build\*.zip
- path: build\*.exe
